#!/bin/zsh

set -eu

action="${1:-on}"
subcmd="${2:-}"
pw="$(cat $HOME/.displays.pw)"

conf() {
  if [ "$(hostname)" = "serpentis" ]; then
  cat <<CONF
Panel:1366x768:COL0:eDP1:none
Halflife:1280x800:COL1:none:pw
*:COL0:shift:0:pw
*:COL1:shift:0:pw
CONF
  else
  cat <<CONF
Lifetab4:1280x800:COL0:none:pw
Nova:800x600:COL0:none:pw
Laptop2:1366x768:COL1:none:none
Laptop1:1366x768:COL1:none:none
Lifetab1:1280x800:COL1:none:pw
SamsungBlack2:1024x600:COL1:none:pw
SamsungBlack1:1024x600:COL1:none:pw
ViewSonic:1280x1024:COL2:none:none
Belinea:1280x1024:COL2:HDMI1:pw
Lifetab2:1280x800:COL2:none:pw
Write:2560x1600:COL2:none:pw:multicol
Samsung:1360x768:COL3:HDMI2:pw
Lenovo:1280x800:COL3:none:pw
Medion:1280x1024:COL4:VGA1:pw
Lifetab3:1280x800:COL4:none:pw
Phone:1920x1080:COL4:none:pw
*:COL0:shift:2036:pw
*:COL1:shift:700:pw
*:COL2:shift:0:pw
*:COL3:shift:700:pw
*:COL4:shift:900:pw
CONF
  fi
}

parseName() {
  cut -d: -f1
}

parseWidth() {
  cut -d: -f2 | cut -dx -f1
}

parseHeight() {
  cut -d: -f2 | cut -dx -f2
}

parseSize() {
  cut -d: -f2
}

parseColumn() {
  cut -d: -f3
}

parseOutput() {
  cut -d: -f4
}

parsePassword() {
  cut -d: -f5
}

parseMulticol() {
  cut -d: -f6
}

parseOutput() {
  cut -d: -f4
}

columnWidth() {
  max=0
  conf | grep "$1" | grep -v "^*" | grep -v "multicol" | parseWidth | while read w; do
    if [ "$max" -lt "$w" ]; then
      max="$w"
    fi
  done

  echo "$max"
}

columnShift() {
  conf | grep "^\*:${1}:shift" | cut -d: -f4
}

columnHeight() {
  sum="$(columnShift "$1")"
  conf | grep "$1" | grep -v "^*" | parseHeight | while read h; do
    sum="$(($sum + $h))"
  done

  echo "$sum"
}

columnStart() {
  sum=0
  conf | grep -B999 "^*:${1}" | grep "^*" | grep -v "$1" | cut -d: -f2 | while read col; do
    sum="$(($sum + $(columnWidth $col)))"
  done

  echo "$sum"
}

framebufferWidth() {
  sum=0
  conf | grep "^*:COL" | cut -d: -f2 | while read col; do
    sum="$(($sum + $(columnWidth $col)))"
  done

  echo "$sum"
}

framebufferHeight() {
  max=0
  conf | grep "^*:COL" | cut -d: -f2 | while read col; do
    if [ "$max" -lt "$(columnHeight $col)" ]; then
      max="$(columnHeight $col)"
    fi
  done

  echo "$max"
}

size() {
  if [ "$1" = "framebuffer" ]; then
    echo "$(framebufferWidth)x$(framebufferHeight)"
  else
    conf | grep "^$1:" | parseSize
  fi
}

monsize() {
  size "$1" | sed -e 's/\(.*\)x\(.*\)/\1\/100x\2\/100/'
}

column() {
  conf | grep "^$1:" | parseColumn
}

output() {
  conf | grep "^$1:" | parseOutput
}

password() {
  conf | grep "^$1:" | parsePassword
}

pos() {
  col="$(column "$1")"
  x="$(columnStart "$col")"
  y="$(columnShift "$col")"

  conf | grep -B99 "$1" | grep ":$col" | grep -v "$1" | parseHeight | while read h; do
    y="$(($y + $h))"
  done

  echo "${x}x$y"
}

panpos() {
  pos "$1" | tr x +
}

port() {
  echo "$((5899 + $(conf | grep -B99 "$1" | wc -l)))"
}

fwdPort() {
  echo "$(($(port $1) + 1000))"
}

startx() {
  uxterm -T displays -e "ssh $1 Xorg -nocursor" &
}

unlock() {
  ssh "$1" 'DISPLAY=:0 xset dpms 0 0 0'
  ssh "$1" 'DISPLAY=:0 xset s 0 0'
  ssh "$1" 'DISPLAY=:0 xset dpms force on'
  ssh "$1" 'DISPLAY=:0 xset b off'
  ssh "$1" 'DISPLAY=:0 killall i3lock || true'
}

lock() {
  ssh "$1" 'killall vncviewer'
  ssh "$1" 'DISPLAY=:0 xset dpms force off'
  ssh "$1" 'DISPLAY=:0 screen -dmS i3lock i3lock'
}

# setupBelina() { }
setupSamsung() { }
setupMedion() { }

setupLaptop1() {
  uxterm -T displays -e "ssh -R $(port Laptop1):localhost:$(port Laptop1) drahflow@192.168.3.109 'export DISPLAY=:0; ~/i3.install/bin/i3-msg workspace 1; ~/i3.install/bin/i3-msg move workspace to output eDP1; vncviewer FullScreen=0 ViewOnly=1 UseLocalCursor=0 geometry=1366x768+0+0 localhost:$(port Laptop1)'" &

  sleep 2

  ssh drahflow@192.168.3.109 'DISPLAY=:0 ~/i3.install/bin/i3-msg floating enable'
  ssh drahflow@192.168.3.109 'DISPLAY=:0 ~/i3.install/bin/i3-msg resize shrink up 10px'
  ssh drahflow@192.168.3.109 'DISPLAY=:0 ~/i3.install/bin/i3-msg resize set 1368 770'
  ssh drahflow@192.168.3.109 'DISPLAY=:0 xdotool mousemove 0 767'
}

setupViewSonic() {
  sleep 10

  uxterm -T displays -e "ssh -R $(port ViewSonic):localhost:$(port ViewSonic) root@192.168.3.8 'export DISPLAY=:0; i3-msg workspace 2; i3-msg move workspace to output HDMI-1; vncviewer FullScreen=0 ViewOnly=1 UseLocalCursor=0 geometry=1280x1024+0+0 localhost:$(port ViewSonic)'" &

  sleep 2

  ssh root@192.168.3.8 'DISPLAY=:0 i3-msg floating enable'
}

setupLaptop2() {
  unlock root@192.168.3.8 || true

  uxterm -T displays -e "ssh -R $(port Laptop2):localhost:$(port Laptop2) root@192.168.3.8 'export DISPLAY=:0; i3-msg workspace 1; i3-msg move workspace to output eDP1; vncviewer FullScreen=0 ViewOnly=1 UseLocalCursor=0 geometry=1366x768+0+0 localhost:$(port Laptop2)'" &

  sleep 2

  ssh root@192.168.3.8 'DISPLAY=:0 i3-msg floating enable'
}

android() {
  port="$1"
  device="$2"
  debian="$3"
  extraEscape="${4:-no}"
  rootingTime="${5:-10}"
  acc="${6:-root@192.168.3.8}"
  fwdPort="$(($port + 1000))"

  # ssh $acc adb -s $device shell ps | grep Xorg || (
  #   ssh root@192.168.3.109 adb -s 30045b283451c100 shell ps | grep zygote || (

  if [ "$extraEscape" = "escape" -a "$subcmd" != "fix" ]; then
    ssh "${acc}" adb -s "$device" shell /data/local/tmp/root.sh
    sleep $rootingTime
  fi

  if [ "$subcmd" != "fix" ]; then
    if [ "$subcmd" != "noboot" ]; then
      ssh "${acc}" adb -s "${device}" shell su -c reboot
      sleep 90;
    fi

    if [ "$action" != "off" -a "$subcmd" != "off" ]; then
      if [ "$extraEscape" = "escape" ]; then
        ssh "${acc}" adb -s "${device}" shell /data/local/tmp/root.sh
        sleep $rootingTime
      fi

      ssh "${acc}" adb -s "${device}" shell su -c ${debian}/start.sh
      sleep 5

      if [ "$extraEscape" = "escape" ]; then
        ssh "${acc}" adb -s "${device}" shell su -c ${debian}/enter.sh\\\\ rm\\\\ -f\\\\ /tmp/.X0-lock
        uxterm -T displays -e "ssh -tt ${acc} adb -s ${device} shell su -c ${debian}/enter.sh\\\\\\\\ /root/X.sh" &
        sleep 15
      else
        ssh "${acc}" adb -s "${device}" shell su -c ${debian}/enter.sh rm -f /tmp/.X0-lock
        uxterm -T displays -e "ssh -tt ${acc} adb -s ${device} shell su -c ${debian}/enter.sh /root/X.sh" &
        sleep 15
      fi
    fi
  fi

  if [ "$action" != "off" -a "$subcmd" != "off" ]; then
    if [ "$extraEscape" = "escape" ]; then
      uxterm -T displays -e "ssh -R ${fwdPort}:localhost:${port} -tt ${acc} socat TCP-CONNECT:127.0.0.1:${fwdPort} SYSTEM:\\'adb -s ${device} shell -e none su -c ${debian}/enter.sh\\\\\\\\\\\\\\\\ /socat.sh\\'" &
      sleep 10
      uxterm -T displays -e "ssh -tt ${acc} adb -s ${device} shell su -c ${debian}/enter.sh\\\\\\\\ /root/vnc.sh" &
    else
      uxterm -T displays -e "ssh -R ${fwdPort}:localhost:${port} -tt ${acc} socat TCP-CONNECT:127.0.0.1:${fwdPort} SYSTEM:\\'adb -s ${device} shell -e none su -c ${debian}/enter.sh /socat.sh\\'" &
      sleep 10
      uxterm -T displays -e "ssh -tt ${acc} adb -s ${device} shell su -c ${debian}/enter.sh /root/vnc.sh" &
    fi
  fi
}

setupSamsungWhite() {
  android "$(port SamsungWhite)" 30045b283451c100 /system/debian no
}

setupSamsungBlack1() {
  android "$(port SamsungBlack1)" 3004575aaf74c100 /system/debian no
}

setupSamsungBlack2() {
  android "$(port SamsungBlack2)" 3004924d2e1b7100 /system/debian no
}

setupLifetab1() {
  android "$(port Lifetab1)" DEA0017625 /data/debian-jessie no
}

setupLifetab2() {
  android "$(port Lifetab2)" DEA0025691 /data/debian-jessie no
}

setupLifetab3() {
  android "$(port Lifetab3)" DEA0001695 /data/debian-jessie no
}

setupLifetab4() {
  android "$(port Lifetab4)" DEA0009624 /data/debian-jessie no
}

setupLenovo() {
  android "$(port Lenovo)" FA49RWJRZLT8FY7H /data/debian-jessie escape
}

setupNova() {
  android "$(port Nova)" 0123456789ABCDEF /data/debian-jessie no
}

setupPhone() {
  uxterm -T displays -e "ssh -R 192.168.2.2:$(fwdPort Phone):localhost:$(port Phone) root@192.168.3.2 sleep 86400" &

  port Phone
}

setupWrite() {
  android "$(port Write)" 2n21i811800000cvj0o0 /data/debian-jessie escape 1
}

setupHalflife() {
  android "$(port Halflife)" DEMX114508 /data/debian-jessie no 1 "root@localhost"
}

setupNeron() {
  android "$(port Neron)" WAWJMZTJQX /data/debian-jessie no 1 "root@localhost"
}

setupLaptops() {
  setupLaptop1 &
  setupLaptop2 &
  setupViewSonic &
}

setupTablets() {
  if [ "$(hostname)" = "serpentis" ]; then
    setupHalflife &
  else
    setupLifetab1 &
    sleep 2
    setupSamsungBlack1 &
    sleep 2
    setupSamsungBlack2 &
    sleep 2
    setupWrite &
    sleep 2
    setupLifetab2 &
    sleep 2
    setupLifetab3 &
    sleep 2
    setupLifetab4 &
    sleep 2
    setupLenovo &
    sleep 2
    setupPhone &
  fi
}

if [ "$action" = "on" ]; then
  xrandr --listmonitors | cut -d' ' -f 3 | grep -v '^$' | grep -v 'eDP1' | while read m; do
    xrandr --delmonitor "$m"
  done

  killall x11vnc || true
  sleep 0.5
  killall -9 x11vnc || true
  sleep 0.5

  if [ "$(hostname)" = "serpentis" ]; then
    xrandr --fb $(size framebuffer) \
      --output eDP1 --pos $(pos Panel) --panning $(size framebuffer)+0+0/$(size Panel)+$(panpos Panel)
  else
    xrandr --fb $(size framebuffer) \
      --output HDMI1 --pos $(pos Belinea) --panning $(size framebuffer)+0+0/$(size Belinea)+$(panpos Belinea) \
      --output HDMI2 --pos $(pos Samsung) --panning $(size Samsung)+$(panpos Samsung)/$(size Samsung)+$(panpos Samsung) \
      --output VGA1 --pos $(pos Medion) --panning $(size Medion)+$(panpos Medion)/$(size Medion)+$(panpos Medion)
  fi

  conf | grep -v "^*" | parseName | while read n; do
    xrandr --setmonitor "$n" "$(monsize "$n")+$(panpos "$n")" "$(output "$n")"
  done

  sleep 5

  conf | grep -v "^*" | parseName | while read n; do
    if [ "$(output "$n")" = "none" ]; then
      if [ "$(password "$n")" = "none" ]; then
        uxterm -T displays -e "while sleep 0.1; do x11vnc -noxfixes -forever -rfbport $(port "$n") -viewonly -localhost -clip $(size "$n")+$(panpos "$n"); done" &
      else
        uxterm -T displays -e "while sleep 0.1; do x11vnc -noxfixes -forever -passwd "$pw" -rfbport $(port "$n") -localhost -clip $(size "$n")+$(panpos "$n"); done" &
      fi
    fi
  done

  sleep 10

  if [ "$(hostname)" = "serpentis" ]; then
    # all manual
  else
    unlock drahflow@192.168.3.109 || true
    unlock root@192.168.3.8 || true

    setupLaptops
  fi
elif [ "$action" = "off" ]; then
  xrandr --listmonitors | cut -d' ' -f 3 | grep -v '^$' | while read m; do
    xrandr --delmonitor "$m"
  done

  xrandr --fb 3920x1024 \
    --output HDMI1 --pos 0x0 --panning 1280x1024+0+0 \
    --output HDMI2 --pos 1280x0 --panning 1360x768+1280+0 \
    --output VGA1 --pos $((1280 + 1360))x0 --panning 1280x1024+$((1280 + 1360))+0

  sleep 5

  if [ "${2:-}" = "hard" ]; then
    conf | grep -v "^*" | parseName | while read n; do
      setup$n || true
    done
  fi

  tablet-brightness off
  lock drahflow@192.168.3.109  || true
  lock root@192.168.3.8  || true
else
  setup$action || true
fi
