#!/bin/sh

set -eu

xrandr --delmonitor VIRTUAL-0
xrandr --delmonitor DVI-D-0-FIXED
xrandr --delmonitor HDMI-0-FIXED
xrandr --delmonitor VIRTUAL-1
xrandr --delmonitor VIRTUAL-2

xrandr --fb 5286x2048 \
  --output DVI-D-0 --pos 1366x0 --panning $((1366+1280))x2048+0+0/1280x1024+1366+0 \
  --output HDMI-0 --pos $((1366 + 1280))x0 --panning 1360x$((768 + 480))+$((1366 + 1280))+0/1360x768+$((1366+1280))+0 \
  --output VGA-0 --pos $((1366 + 1280 + 1360))x0 --panning 1280x1024+$((1366 + 1280 + 1360))+0

xrandr --setmonitor VIRTUAL-0 1366/376x768/211+0+0 none
xrandr --setmonitor DVI-D-0-FIXED 1280/376x1024/301+1366+0 DVI-D-0
xrandr --setmonitor HDMI-0-FIXED 1360/160x768/90+$((1366+1280))+0 HDMI-0
xrandr --setmonitor VIRTUAL-1 800/100x480/50+$((1366+1280))+768 none
xrandr --setmonitor VIRTUAL-2 1280/376x1024/301+1366+1024 none

uxterm -e "while sleep 0.1; do x11vnc -forever -viewonly -localhost -clip 1366x768+0+0; done" &
uxterm -e "while sleep 0.1; do x11vnc -forever -passwd XXX -rfbport 5901 -viewonly -localhost -clip 800x480+$((1366 + 1280))+768; done" &
uxterm -e "while sleep 0.1; do x11vnc -forever -rfbport 5902 -viewonly -localhost -clip 1280x1024+1366+1024; done" &
uxterm -e "ssh -R 192.168.2.2:5900:localhost:5901 root@192.168.3.2" &

sleep 10

ssh drahflow@192.168.3.109 'DISPLAY=:0 xset dpms 0 0 0'
ssh drahflow@192.168.3.109 'DISPLAY=:0 xset s 0 0'
ssh drahflow@192.168.3.109 'DISPLAY=:0 xset dpms force on'
ssh drahflow@192.168.3.109 'DISPLAY=:0 killall i3lock'
ssh drahflow@192.168.3.109 'DISPLAY=:0 xrandr --output HDMI1 --auto --right-of eDP1 --rotate inverted'
uxterm -e "ssh -R 5900:localhost:5900 drahflow@192.168.3.109 'export DISPLAY=:0; i3.install/bin/i3-msg workspace 1; i3.install/i3-msg move workspace to output eDP1; vncviewer FullScreen=0 ViewOnly=1 UseLocalCursor=0 geometry=1366x768+0+0 localhost'" &

sleep 2

ssh drahflow@192.168.3.109 'DISPLAY=:0 i3.install/bin/i3-msg floating enable'
ssh drahflow@192.168.3.109 'DISPLAY=:0 i3.install/bin/i3-msg resize shrink up 6px'
ssh drahflow@192.168.3.109 'DISPLAY=:0 i3.install/bin/i3-msg resize set 1368 770'

uxterm -e "ssh -R 5902:localhost:5902 drahflow@192.168.3.109 'export DISPLAY=:0; i3.install/bin/i3-msg workspace 2; i3.install/i3-msg move workspace to output HMDI1; vncviewer FullScreen=0 ViewOnly=1 UseLocalCursor=0 geometry=1280x1024+0+0 localhost:5902'" &

sleep 2

ssh drahflow@192.168.3.109 'DISPLAY=:0 i3.install/bin/i3-msg floating enable'
ssh drahflow@192.168.3.109 'DISPLAY=:0 i3.install/bin/i3-msg resize shrink up 6px'
ssh drahflow@192.168.3.109 'DISPLAY=:0 i3.install/bin/i3-msg resize set 1282 1026'

