#!/bin/zsh

if [ -r "$1" ]; then
  tex="$1"
  root="${1//.tex}"
  root="${root//.latex}"
elif [ -r "${1//.}.tex" ]; then
  tex="${1//.}.tex";
  root="${1//.}"
elif [ -r "$1.tex" ]; then
  tex="$1.tex";
  root="$1"
else
  tex="$1.latex";
  root="$1"
fi

latex "$tex" &&
dvips "$root".dvi &&
ps2pdf "$root".ps
